[package]
name = "websockets"
version = "1.0.0"
publish = false
edition.workspace = true

[dependencies]
actix-web = "4"
actix-ws = "0.3"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
