name: Examples

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check-examples:
    name: Check examples
    runs-on: ubuntu-latest

    steps:
      # required packages
      - run: sudo apt install sqlite3

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0

      - name: Install just
        uses: taiki-e/install-action@bffeee26d4db9be238a4ea78d8826604ebcb594d # v2.82.5
        with:
          tool: just

      - name: Test examples
        env:
          RUSTFLAGS: -A dead-code -A unused-variables
        run: just test
