name: Examples

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]
  push:
    branches: [main]

jobs:
  check-examples:
    name: Check examples
    runs-on: ubuntu-latest

    steps:
      # required packages
      - run: sudo apt install sqlite3

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4

      - name: Install just
        uses: taiki-e/install-action@68675c5a5f1a6950c3975d33f3ae0ef155e5bf3d # v2.68.15
        with:
          tool: just

      - name: Test examples
        env:
          RUSTFLAGS: -A dead-code -A unused-variables
        run: just test
