name: Examples

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check-examples:
    name: Check examples
    runs-on: ubuntu-latest

    steps:
      # required packages
      - run: sudo apt install sqlite3

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0

      - name: Install just
        uses: taiki-e/install-action@1329c298aa20c3257846c9b2e0e55967df3e3c37 # v2.75.25
        with:
          tool: just

      - name: Test examples
        env:
          RUSTFLAGS: -A dead-code -A unused-variables
        run: just test
